### ISSUE TITLE
Error when importing the package to Unity

### ISSUE THREAD

**Issue by waffwrw** [Lachee/discord-rpc-unity#11]
I Get this error when I import the package from the the Unity Package Manager via Git URL

error CS1566: Error reading resource 'DiscordRPC.xml' -- 'Could not find a part of the path 'Packages\com.lachee.discordrpc\Runtime\DiscordRPC.xml'.'

**Comment by Lachee** [comment]
Hello thanks for this issue. I have reproduced it and investigating it.

Can you give the unity version you're using ?

**Comment by waffwrw** [comment]
I'm using Unity Version 2021.3.23f1

**Comment by waffwrw** [comment]
are there any updates?

**Comment by Lachee** [comment]
ah sorry been super busy last 2 weeks. I'll look into it today for you :)

**Comment by waffwrw** [comment]
tysm!!

**Comment by Lachee** [comment]
error closing. Didn't realise `fixes #issue` closed issues automagically

**Comment by Lachee** [comment]
This has been resolved with [Release v1.1.1](https://github.com/Lachee/discord-rpc-unity/releases/tag/v1.1.1)

**Comment by webik150** [comment]
I still have an issue with this. Same error, only it doesn't necessarily appear when importing, rather once I compile my scripts (after any code change). From what I understand Unity deletes the file since it can't 

`error CS1566: Error reading resource 'DiscordRPC.xml' -- 'Could not find a part of the path 'C:\pathtoproject\Packages\com.lachee.discordrpc\Runtime\DiscordRPC.xml'.'`

I seem to have fixed this by manually creating the desired path and copying the files there (along with a .meta file from version 1.0.3).
